### PR TITLE
Gen/gen config

### PR DESCRIPTION
**Pull request by jackturner83**
# Create Generate Config function

## Description

This is the main function which calls both create_targeted_paths_list and write_yaml_of_paths_list functions. 

## Type of Change

- [x] Feature
- [ ] Bug fix
- [ ] Documentation

## Contributors

- @jackturner83

## Blocked by

- #71
- #69

## Reminder

 - All GitHub Actions should be in a passing state before any pull request is merged.
 - All PRs must be reviewed by at least one team member and one member of the Integration team!
 - Any issues this PR closes are tagged in the description!

### CODE REVIEW

**Review by Nathandloria — APPROVED** [review]

**Review by Yanqiao4396 — APPROVED** [review]
Nice

**Review by Yanqiao4396 — CHANGES_REQUESTED** [review]
Check lint please

**Review by Yanqiao4396 — DISMISSED** [review]

**Comment by Michionlion** [comment]
@jackturner83 you should be good now to merge `main` into this branch, resolve conflicts, and make sure things are correct! Once that's done, and everything passes, you should be good to merge (but make sure you get the required reviews).

**Review by Nathandloria — APPROVED** [review]
Lets gooo good work guys.

**Review by Yanqiao4396 — APPROVED** [review]

**Review by Michionlion — APPROVED** [review]
This looks great, thanks @jackturner83!

**Pull request merged**
