### PR TITLE
WIP: Feature/json output

### PR DESCRIPTION
**Pull request by ullrichd21**
# Json output

## Description
adds `--report/-r <file>` to create a machine readable output.

**Please delete the other branch feature/json-output**

Example output (shortened):
```
{
  "passed_checks": [
    [
      "Complete all TODOs in LICENSE",
      true,
      ""
    ],
    [
      "Complete all TODOs in mkdocs.yml",
      true,
      ""
    ],
    [
      "Complete all TODOs in pyproject.toml",
      true,
      ""
    ],
],
"failed_checks": [
    [
      "Complete all TODOs in gatorgrade.yml",
      false,
      "Found 152 fragment(s) in the gatorgrade.yml or the output"
    ],
    [
      [
        "--description",
        "Complete all TODOs in poetry.lock",
        "MatchFileFragment",
        "--fragment",
        "TODO",
        "--count",
        "0",
        "--exact",
        "--directory",
        ".",
        "--file",
        "poetry.lock"
      ],
      false,
      "Traceback (most recent call last):\n  File \"C:\\Users\\Da..."
    ]
],
"percent": 47
}
```

## Linked Issues

closes: #89 

## Type of Change

- [x] Feature
- [ ] Bug fix
- [ ] Documentation

## Contributors

- @ullrichd21 

## Reminder

 - All GitHub Actions should be in a passing state before any pull request is merged.
 - All PRs must be reviewed by at least one team member and one member of the Integration team!
 - Any issues this PR closes are tagged in the description!

### CODE REVIEW

**Comment by gkapfham** [comment]
Hi @ullrichd21, thanks for creating this PR.

Can you give an example of the output that it produces in the PR, perhaps for the hello-world example?

Also, do you have any idea as to whether or not there are test cases that cover all of the new code you added?

Right now I don't think that this project has code coverage tracking, but it would be nice if you can anecdotally show that you have tested all of the new functionality.

Finally, I'm pretty sure that @mariakimheinert and @Michionlion will not have time to review this PR.

However, I am glad to review the PR and continue the discussion here.

Thanks!

**Comment by ullrichd21** [comment]
> Hi @ullrichd21, thanks for creating this PR.
> 
> Can you give an example of the output that it produces in the PR, perhaps for the hello-world example?
> 
> Also, do you have any idea as to whether or not there are test cases that cover all of the new code you added?
> 
> Right now I don't think that this project has code coverage tracking, but it would be nice if you can anecdotally show that you have tested all of the new functionality.
> 
> Finally, I'm pretty sure that @mariakimheinert and @Michionlion will not have time to review this PR.
> 
> However, I am glad to review the PR and continue the discussion here.
> 
> Thanks!

Added some tests as well as a sample output, however I did shorten it to fit better, if you'd like a full output still I can provide that.

**Comment by gkapfham** [comment]
Hello @ullrichd21, thanks for creating this PR. I appreciate your help!

I aim to review the PR and try out your version of the tool by the end of the upcoming weekend.

I've created a bunch of different projects that are using `gatorgrade` and I want to test the tool carefully on each of them.

If this does not work for your schedule, please let me know.

Also, can you suggest at least one additional person who would be a good candidate for reviewing this PR?

**Comment by ullrichd21** [comment]
That sounds good, I've got no timeline for it. As this was a feature suggested by Prof. Luman, he might be a good person to include as a reviewer to see if it meets his requirements?

**Comment by dluman** [comment]
One thing I can think here -- and it's _very_ minor -- is to minify the output; I might intend for this to make a transit over a network (i.e. to a remote server via webhook). 

Add me as a reviewer and test and render feedback. This would help greatly with the application that I'm writing alongside the `CMPSC 600` students this semester.

**Comment by ullrichd21** [comment]
> One thing I can think here -- and it's _very_ minor -- is to minify the output; I might intend for this to make a transit over a network (i.e. to a remote server via webhook). 
> 
> Add me as a reviewer and test and render feedback @ullrichd21. This would help greatly with the application that I'm writing alongside the `CMPSC 600` students this semester.
> 
> I didn't see this PR due to not being tagged -- so thanks for reminding me that this existed, @gkapfham.

That's a good point, let me see what I can do and I'll tag you as a reviewer from here on out.

**Pull request closed without merging**
