### PR TITLE
Delete the root period

### PR DESCRIPTION
**Pull request by Yanqiao4396**
# Root period delete

## Description

The root directory in the paths users want is represented by a period. However, it's useless to users. So replace it with an empty string

## Linked Issues

closes: #00

## Type of Change

- [ ] Feature
- [x] Bug fix
- [ ] Documentation

## Contributors

- @Yanqiao4396 

## Reminder

 - All GitHub Actions should be in a passing state before any pull request is merged.
 - All PRs must be reviewed by at least one team member and one member of the Integration team!
 - Any issues this PR closes are tagged in the description!

### CODE REVIEW

**Review by Michionlion — APPROVED** [review]
This is a great quality of life change! Thanks, @Yanqiao4396!

**Review by mariakimheinert — APPROVED** [review]
Thank you for this hotfix, @Yanqiao4396!

**Review by anthonygc — APPROVED** [review]
Looks good!

**Review by Michionlion — APPROVED** [review]
This looks great! Thank you for the fix, @Yanqiao4396!

**Pull request merged**
