### PR TITLE
feat: Automatic PyPI Publishing using Tags and add Auto Releasing

### PR DESCRIPTION
**Pull request by PCain02**
# Automatic PyPI Publishing using Tags and add Auto Releasing

## Description

**YOU SHOULD TEST THIS IN YOUR OWN FORK**  

This PR adds the ability to publish to PyPI automatically when using tags. `tag_publish.yml` and `test-publish.yml` were the main targets of the PR. The lowercase `t` tag will be used for test publishing and the lowercase `v` tag is for real publishing. They should look like t0.7.1 and v0.7.1

The commands to use this are as follows where the version number is replaced with the next sequential version.

`poetry version 0.3.1`
`git add pyproject.toml`
`git commit -m "Chore: Bump version to 0.3.1"`
`git tag t0.3.1`
`git push origin t0.3.1`

You will know it worked if [Test PyPI](https://test.pypi.org/project/gatorgrade/) has updated the version number

Note:  Do not use the `v` tag to test the PR because that will cause a new release which is not ideal.

At the same time you should see the release number go up. This is why you should do it in your own fork.
image

## Linked Issues

Closes: #137 

## Type of Change

- [X] Feature
- [ ] Bug fix
- [ ] Documentation

## Contributors

- @PCain02

### CODE REVIEW

**Comment by CalebKendra** [comment]
This PR needs a secret key to work in the `publish.yml` file.

I lack experience in Pypi and needed to approve this. Potentially another TL could help?

**Comment by rebekahrudd** [comment]
Should we test this in your fork?

I ran into issues because I was in your fork but then I couldn't push to your fork to test it. Here's my output:
pallas_tag feature

**Review by rebekahrudd — APPROVED** [review]
This worked on Linux:
pypi

**Comment by gkapfham** [comment]
Hello @PCain02 can you seek out confirmation that this works if the person who performs the release is running MacOS, as @AlishChhetri has suggested?

**Comment by PCain02** [comment]
> @PCain02, please confirm that this feature works on macOS. I see you’ve tested it on Windows, and Rebekah confirmed it on Linux. We just need a macOS test to complete the cross-platform verification. The feature looks great, and I don’t see any issues with the implementation.
> 
> One question for clarification: does any instance of a v tag trigger a release to PyPI, or only when that tag is committed to the main branch? For instance, if someone on a feature branch uses a v tag, would it publish to PyPI without being merged into main?
> 
> Thank you for clarifying, and I apologize if it’s a basic question!

This is a super interesting question and I did not even think of that. I just tested it and yes it does seem you can tag in any branch and publish it to PyPI. I never even considered this as an issue but would it be better if there was some sort of check that the person is in the main branch before publishing? Thanks for bringing this to my attention!

**Comment by PCain02** [comment]
> Hello @PCain02 can you seek out confirmation that this works if the person who performs the release is running MacOS, as @AlishChhetri has suggested?

Yes! I added @Chezka109 @hemanialaparthi and @dyga01 all MacOS users very good at testing. If they would be so kind I would appreciate the testing!

**Review by rebekahrudd — APPROVED** [review]
It worked on Linux

Tagging the new version:
Screenshot from 2024-11-22 22-22-24

Updating on pypi:
image

**Review by boulais01 — APPROVED** [review]

**Comment by PhilipOlwoc** [comment]
Tested and this works on Mac.

**Review by PhilipOlwoc — APPROVED** [review]
Tested this and it works on Mac.

**Pull request merged**
