### PR TITLE
Add Path Attribute to the CheckResult and Test Customized Insight Key Value Pair

### PR DESCRIPTION
**Pull request by Yanqiao4396**
# Add path attributes to  the CheckResult

## Description

Path attribute helps to locate which file a command belongs to. Add path attribute to the CheckResult to easily fetch it in the json report. Also there is a tiny test of a customized json key under the check. It proves gatorgrade's capability on creating some useful key like `learning objective`

here is an example output of JSON report where the `objective: TODO` is specified under the check of yaml file

Screenshot 2023-07-05 at 9 23 37 PM

Screenshot 2023-07-05 at 9 21 59 PM

## Linked Issues

closes: #00

## Type of Change

- [x] Feature
- [ ] Bug fix
- [ ] Documentation

## Contributors

- @

## Reminder

 - All GitHub Actions should be in a passing state before any pull request is merged.
 - All PRs must be reviewed by at least one team member and one member of the Integration team!
 - Any issues this PR closes are tagged in the description!

### CODE REVIEW

**Comment by gkapfham** [comment]
Hi @Yanqiao4396, thanks for adding this feature. I can see the purpose of what you are adding. I will go ahead and approve this in a moment. However, I wanted to ask an additional question: is it possible to generalize this so that you can tell your feature that generates the JSON exactly what extra attributes you want to have saved? Right now, this works for the new `objective` attribute. But, what is someone has something similar but with a slightly different name? Or, what if they break their learning objectives into multiple attributes? Is there any way to make this more general-purpose? Please let me know what you think!

**Review by gkapfham — APPROVED** [review]
Thanks for adding this feature. I can see how it helps you to achieve your short-term goals of shipping a fully functioning "data analysis solution" and thus it is fine for you to merge this when you have time.

**Comment by gkapfham** [comment]
Also, @Yanqiao4396 does you example illustrate how you added the `Path` attribute to the JSON?

**Comment by Yanqiao4396** [comment]
> Hi @Yanqiao4396, thanks for adding this feature. I can see the purpose of what you are adding. I will go ahead and approve this in a moment. However, I wanted to ask an additional question: is it possible to generalize this so that you can tell your feature that generates the JSON exactly what extra attributes you want to have saved? Right now, this works for the new `objective` attribute. But, what is someone has something similar but with a slightly different name? Or, what if they break their learning objectives into multiple attributes? Is there any way to make this more general-purpose? Please let me know what you think!

Thank you for your message here. here `objective` attribute is just an example. The truth is you can have any kind of attribute with value and as many as you want. So I'd like to say this feature generates whatever you have wanted to save.For the multiple objectives scenario, this feature still eagerly whatever you put into the json.

I will give you more example of variety of scenarios soon

**Comment by Yanqiao4396** [comment]
```
{
  "amount_correct": 11,
  "percentage_score": 58,
  "checks": [
    {
      "description": "Ensure that the main.py file exists in the tree/tree/ directory",
      "check": "ConfirmFileExists",
      "status": true,
      "path": "tree/tree/main.py"
    },
    {
      "description": "Complete all TODOs, remove the TODO markers, and rewrite comments for tree.py",
      "check": "MatchFileFragment",
      "objective": "TODO",
      "options": {
        "fragment": "TODO",
        "count": 0,
        "exact": true
      },
      "status": false,
      "path": "tree/tree/main.py",
      "diagnostic": "Found 1 fragment(s) in the main.py or the output while expecting exactly 0"
    },
    {
      "description": "Create a sufficient number of docstring (i.e., multiple-line) comments in tree.py",
      "check": "CountMultipleLineComments",
      "options": {
        "language": "Python",
        "count": 3,
        "exact": false
      },
      "status": true,
      "path": "tree/tree/main.py"
    },
    {
      "description": "Create a sufficient number of single-line comments in tree.py",
      "check": "CountSingleLineComments",
      "objective": "single-line comment",
      "options": {
        "language": "Python",
        "count": 5,
        "exact": false
      },
      "status": true,
      "path": "tree/tree/main.py"
    },
    {
      "description": "Pass the source code formatting checks run by black",
      "lint": "black",
      "command": "cd tree && poetry run task black",
      "status": false,
      "diagnostic": "would reformat tree/issue.py\n     \n     Oh no! 💥 💔 💥\n     1 file would be reformatted, 2 files would be left unchanged."
    },
    {
      "description": "Pass the linting checks run by flake8",
      "lint": "flake8",
      "command": "cd tree && poetry run task flake8",
      "status": false,
      "diagnostic": "tree/issue.py:11:1: E302 expected 2 blank lines, found 0\n     tree/issue.py:28:1: E302 expected 2 blank lines, found 1\n     tree/issue.py:205:57: E231 missing whitespace after ':'\n     tree/issue.py:208:1: W293 blank line contains whitespace\n     tree/issue.py:217:5: E301 expected 1 blank line, found 0\n     tree/issue.py:222:1: W293 blank line contains whitespace\n     tree/issue.py:251:34: E225 missing whitespace around operator\n     tree/issue.py:266:5: E128 continuation line under-indented for visual indent\n     tree/issue.py:274:1: W293 blank line contains whitespace"
    },
    {
      "description": "Pass the import checks run by isort",
      "command": "cd tree && poetry run task isort",
      "status": false,
      "diagnostic": "ERROR: /home/runner/work/computer-science-400-fall-2022-p7-file-system-traversal-Yanqiao4396/computer-science-400-fall-2022-p7-file-system-traversal-Yanqiao4396/tree/tree/issue.py Imports are incorrectly sorted and/or formatted."
    },
    {
      "description": "Pass the linting checks run by mypy",
      "command": "cd tree && poetry run task mypy",
      "status": false,
      "diagnostic": "tree/issue.py:10: error: Library stubs not installed for \"yaml\" (or incompatible with Python 3.10)\n     tree/issue.py:10: note: Hint: \"python3 -m pip install types-PyYAML\"\n     tree/issue.py:10: note: (or run \"mypy --install-types\" to install all missing stub packages)\n     tree/issue.py:10: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports\n     tree/issue.py:37: error: Incompatible return value type (got \"Tuple[Github, Optional[str]]\", expected \"Tuple[Github, str]\")\n     Found 2 errors in 1 file (checked 3 source files)"
    },
    {
      "description": "Pass the linting checks run by pydocstyle",
      "command": "cd tree && poetry run task pydocstyle",
      "status": true
    },
    {
      "description": "Pass the linting checks run by pylint",
      "command": "cd tree && poetry run task pylint",
      "status": false,
      "diagnostic": "************* Module /home/runner/work/computer-science-400-fall-2022-p7-file-system-traversal-Yanqiao4396/computer-science-400-fall-2022-p7-file-system-traversal-Yanqiao4396/tree/.pylintrc\n     .pylintrc:1:0: R0022: Useless option value for '--disable', 'no-absolute-import' was removed from pylint, see https://github.com/PyCQA/pylint/pull/4942. (useless-option-value)\n     ************* Module tree.issue\n     tree/issue.py:208:0: C0303: Trailing whitespace (trailing-whitespace)\n     tree/issue.py:222:0: C0303: Trailing whitespace (trailing-whitespace)\n     tree/issue.py:274:0: C0303: Trailing whitespace (trailing-whitespace)\n     \n     -----------------------------------\n     Your code has been rated at 9.79/10"
    },
    {
      "description": "Pass the linting checks run by pymarkdown",
      "command": "cd tree && poetry run task markdownlint",
      "status": true
    },
    {
      "description": "Run hello world",
      "command": "ech \"hello\"",
      "status": false,
      "diagnostic": "/bin/sh: 1: ech: not found"
    },
    {
      "description": "Ensure that the reflection.md file exists in the writing/ directory",
      "check": "ConfirmFileExists",
      "status": true,
      "path": "writing/reflection.md"
    },
    {
      "description": "Complete all TODOs, remove the TODO markers, and rewrite comments for the reflection",
      "check": "MatchFileFragment",
      "options": {
        "fragment": "TODO",
        "count": 0,
        "exact": true
      },
      "status": true,
      "path": "writing/reflection.md"
    },
    {
      "description": "Delete the 'Add Your Name Here' prompt in the reflection file",
      "check": "MatchFileFragment",
      "options": {
        "fragment": "Add Your Name Here",
        "count": 0,
        "exact": true
      },
      "status": true,
      "path": "writing/reflection.md"
    },
    {
      "description": "Write a minimum number of meaningful words in the reflection",
      "check": "CountFileWords",
      "options": {
        "count": 800,
        "exact": false
      },
      "status": false,
      "path": "writing/reflection.md",
      "diagnostic": "Found 532 word(s) in total of file reflection.md"
    },
    {
      "description": "Confirm that the markdown file has the correct number of headers",
      "check": "CountMarkdownTags",
      "options": {
        "tag": "heading",
        "count": 15,
        "exact": false
      },
      "status": true,
      "path": "writing/reflection.md"
    },
    {
      "description": "Confirm that the markdown file has the correct number of fenced code blocks",
      "check": "CountMarkdownTags",
      "options": {
        "tag": "code_block",
        "count": 6,
        "exact": false
      },
      "status": true,
      "path": "writing/reflection.md"
    },
    {
      "description": "Have at least a specific minimum of commits in repository",
      "check": "CountCommits",
      "options": {
        "count": 10
      },
      "status": true
    }
  ]
}
```

**Pull request merged**
