### PR TITLE
feat: filtering specific checks

### PR DESCRIPTION
**Pull request by Chezka109**
# Filtering Specific Checks

## Description

This feature adds the ability to filter GatorGrade results to show only the failing checks when running the command. By including a flag such as `--show-failures`, users will be able to see just the errors, which will make it easier to focus on the areas that need improvement without sifting through the passing checks. In addition to this, users can use the flag `--check-include` to show only a specific check and `--check-exclude` to remove specific checks when gatorgrade runs.

## Linked Issues

closes: #139 

## Type of Change

- [x] Feature
- [ ] Bug fix
- [ ] Documentation

## Contributors

- @Chezka109
- @HoangTrang150302

## Reminder

 - All GitHub Actions should be in a passing state before any pull request is merged.
 - All PRs must be reviewed by at least one team member and one member of the Integration team!
 - Any issues this PR closes are tagged in the description!

### CODE REVIEW

**Comment by Chezka109** [comment]
Update: trying to implement the diagnostic message for failing checks when `--check-include` and `--check-exclude` runs and trying to get the overall status percentage of checks to show up when `--show-failures` runs.

**Comment by Chezka109** [comment]
@AlishChhetri I'm having trouble figuring out why the diagnostic message for `--check-include` and `--check-exclude` isn't  showing up and why the report box isn't showing up for `--show-failures`

**Comment by gkapfham** [comment]
Hello @Chezka109 can you please give us a status update on the work for this branch? It does not look completed and thus I converted it to a draft PR. Also, I think that this PR needs some screenshots to demonstrate what is and is not working and how a person would actually use the feature that this PR implements.

**Comment by gkapfham** [comment]
Also @Chezka109 please note that this branch has conflicts that must be resolved before it can be merged. Can you please investigate these issues? Thanks so much, I appreciate your help.

**Pull request closed without merging**
