### PR TITLE
Create _init_.py file

### PR DESCRIPTION
**Pull request by LiamBlack3**
# Input team create __init__.py file

## Description

Created blank __init__.py file for input team

## Type of Change

- [x] Feature
- [ ] Bug fix
- [ ] Documentation

## Contributors

- @LiamBlack3 

## Reminder

 - All GitHub Actions should be in a passing state before any pull request is merged.
 - All PRs must be reviewed by at least one team member and one member of the Integration team!
 - Any issues this PR closes are tagged in the description!

### CODE REVIEW

**Review by PaigeCD — APPROVED** [review]
I think this fine.

**Review by MAbraham24 — DISMISSED** [review]
This is fine

**Review by laurennevill — COMMENTED** [review]
You will need to add a docstring into the file or it will conflict with pydocstyle which is something the integration team has specified as a dependency. This doesn't have to be anything fancy it just needs to follow the standard format for a docstring.

**Comment by noorbuchi** [comment]
I think the changes here are too little to be included in a PR by themselves. Please add more work to this PR before merging.

**Review by MAbraham24 — APPROVED** [review]
This looks better.

**Comment by mariakimheinert** [comment]
@LiamBlack3, @noorbuchi has raised a good point--this file is probably better suited to be included in a PR with some more changes. For example, it could be in a branch with the beginnings of the input team's code. If you agree, @LiamBlack3, would you please close this pull request?

**Pull request closed without merging**
