### PR TITLE
Bug: json dumps replaces str

### PR DESCRIPTION
**Pull request by Yanqiao4396**
used to use dict type and failed as dict is not
equal to json type. Now put json type into JSON_REPORT correctly

# json dumps
## Description
Store json dumps instead of dictionary into the JSON_REPORT environment variable

## Linked Issues

closes: #00

## Type of Change

- [ ] Feature
- [x] Bug fix
- [ ] Documentation

## Contributors

- @Yanqiao4396 

## Reminder

 - All GitHub Actions should be in a passing state before any pull request is merged.
 - All PRs must be reviewed by at least one team member and one member of the Integration team!
 - Any issues this PR closes are tagged in the description!

### CODE REVIEW

**Review by gkapfham — APPROVED** [review]
Okay, I'm glad to approve this small change.

You mention that something failed. What was it that failed? How did it fail? Can you please provide a few more details?

Thanks!

**Review by Michionlion — APPROVED** [review]

**Comment by Yanqiao4396** [comment]
> Okay, I'm glad to approve this small change.
> 
> You mention that something failed. What was it that failed? How did it fail? Can you please provide a few more details?
> 
> Thanks!

When I tried to read json from env with `json.load` cmd, error message like `json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)` shows up. It's because the content of env is dictionary other than json. That's the error. I failed to load the json

**Comment by Yanqiao4396** [comment]
@Michionlion , @gkapfham . Thank both of u for reviewing this PR. I just removed indent in `json.dumps` command.The string was multi lines with indentation arg in` json.dumps` and turns out the `GitHub_ENV` doesn't support multi-line strings and it threw error. So I removed indentation arg and made this string single line. It worked well after this change and BranchWrite could read JSON_REPORT successfully like below
image

**Review by gkapfham — APPROVED** [review]
Approved.

**Review by Michionlion — APPROVED** [review]

**Pull request merged**
